version: '2'
services:
  db:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    volumes:
      - ./data:/bitnami
  voiceit:
    build: .
    restart: always
    links:
      - db
    environment:
      - VOICEITEMAILUSERNAME=
      - VOICEITEMAILPASSWORD=
      - VOICEITADMINEMAIL=
      - VOICEITURL=http://localhost:8080
      - VOICEITADMINPASSWORD=
      - REDISLOCATION=redis://db:6379
      - TMPDIR=/tmp
    ports:
      - '8080:8080'
